mapi.wow_event = {
	-- Generic --
	WOW_UPDATE = "UPDATE",
	WOW_ADDON_LOADED = "ADDON_LOADED",

	-- Gathering skill --
	WOW_CHAT_MSG_SKILL = "CHAT_MSG_SKILL",
	
	-- Unit tracking --
	WOW_UNIT_AURA = "UNIT_AURA",
	WOW_UNIT_FLAGS = "UNIT_FLAGS",
	WOW_UNIT_HEALTH = "UNIT_HEALTH",
	WOW_UNIT_COMBAT = "UNIT_COMBAT",
	WOW_UNIT_FACTION = "UNIT_FACTION",
	WOW_UNIT_CASTEVENT = "UNIT_CASTEVENT",
	WOW_UNIT_HAPPINESS = "UNIT_HAPPINESS",
	WOW_UNIT_MODEL_CHANGED = "UNIT_MODEL_CHANGED",
	WOW_UNIT_PORTRAIT_UPDATE = "UNIT_PORTRAIT_UPDATE",
	WOW_PLAYER_TARGET_CHANGED = "PLAYER_TARGET_CHANGED",
	WOW_UPDATE_MOUSEOVER_UNIT = "UPDATE_MOUSEOVER_UNIT",
}